name: demo-birthday-alert
services:
  node:
    type: node:18
    ports:
      - 3000:3000
    run:
      - npm install -g pm2
      - npm install
      - npm run build
      - npm run schema:sync
      - pm2 start dist/main.js
  database:
    type: mysql
  pma:
    type: phpmyadmin
tooling:
  npm:
    service: node
  node:
    service: node
  pm2:
    service: node
proxy:
  node:
    - demo-birthday-alert.lndo.site:3000
  pma:
    - demo-birthday-alert.pma.lndo.site
