name: demo-birthday-alert
services:
  node:
    type: node:18
    ports:
      - 3000:3000
    build:
      - npm install -g pm2
    run:
      - npm install
      - cp .env.example .env
      - npm run build
      - npm run schema:sync
      - pm2 start npm --name "nestjs" -- run start:prod
  database:
    type: mysql
  redis:
    type: redis
  pma:
    type: phpmyadmin
  swagger:
    type: lando
    moreHttpPorts:
      - 8080
    services:
      image: swaggerapi/swagger-ui
      command: /docker-entrypoint.sh nginx -g "daemon off;"
      ports:
        - 8080
      volumes:
        - ./demo-birthday-alert.openapi.json:/usr/share/nginx/html/openapi.json
      environment:
        SWAGGER_JSON_URL: /openapi.json
tooling:
  npm:
    service: node
  node:
    service: node
  pm2:
    service: node
proxy:
  node:
    - demo-birthday-alert.lndo.site:3000
  pma:
    - pma.demo-birthday-alert.lndo.site
  swagger:
    - swagger.demo-birthday-alert.lndo.site:8080
